{
  "openapi": "3.0.0",
  "info": {
    "title": "Influencers App API",
    "version": "1.0.0",
    "description": "API para gerenciamento de influenciadores e campanhas."
  },
  "servers": [
    {
      "url": "http://localhost/api/v1",
      "description": "Servidor local"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/cadastrar": {
      "post": {
        "summary": "Cadastro de usuário",
        "description": "Registra um novo usuário no sistema (seus dados).",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" },
                  "email": { "type": "string" },
                  "password": { "type": "string" }
                },
                "required": ["nome", "email", "password"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Usuário registrado com sucesso."
          },
          "400": {
            "description": "Erro no cadastro do usuário."
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Login de usuário",
        "description": "Realiza o login de um usuário e retorna um token JWT (seus dados cadastrados previamente).",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": { "type": "string" },
                  "password": { "type": "string" }
                },
                "required": ["email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login realizado com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": { "type": "string" }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Credenciais inválidas."
          }
        }
      }
    },
    "/sistema/influencer/criar": {
      "post": {
        "summary": "Cadastrar influenciador",
        "description": "Adiciona um novo influenciador ao sistema.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" },
                  "usuario_instagram": { "type": "string" },
                  "quantidade_seguidores": { "type": "integer" },
                  "categoria": { "type": "string" }
                },
                "required": ["nome", "usuario_instagram", "quantidade_seguidores", "categoria"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Influenciador cadastrado com sucesso."
          }
        }
      }
    },
    "/sistema/influencer": {
      "get": {
        "summary": "Lista de influenciadores",
        "description": "Obtém a lista de influenciadores cadastrados no sistema.",
        "responses": {
          "200": {
            "description": "Lista de influenciadores retornada com sucesso."
          }
        }
      }
    },
    "/sistema/campanhas/criar": {
      "post": {
        "summary": "Cadastrar campanha",
        "description": "Cria uma nova campanha de marketing.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" },
                  "orcamento": { "type": "number" },
                  "descricao": { "type": "string" },
                  "data_inicio": { "type": "string", "format": "date" },
                  "data_fim": { "type": "string", "format": "date" }
                },
                "required": ["nome", "orcamento", "descricao", "data_inicio", "data_fim"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Campanha cadastrada com sucesso."
          }
        }
      }
    },
    "/sistema/campanhas": {
      "get": {
        "summary": "Lista de campanhas",
        "description": "Obtém a lista de campanhas disponíveis.",
        "responses": {
          "200": {
            "description": "Lista de campanhas retornada com sucesso."
          }
        }
      }
    },
    "/sistema/campanhas/vincular-influenciadores/{campanha_id}": {
      "post": {
        "summary": "Vincular influenciadores à campanha",
        "description": "Associa influenciadores a uma campanha específica.",
        "parameters": [
          {
            "name": "campanha_id",
            "in": "path",
            "required": true,
            "description": "ID da campanha para vinculação.",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "influenciador_ids": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    }
                  }
                },
                "required": ["influenciador_ids"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Influenciadores associados à campanha com sucesso."
          },
          "400": {
            "description": "Erro na vinculação dos influenciadores."
          }
        }
      }
    },
    }
}
